import { Game } from '@/types/game';

export const games: Game[] = [
  {
    id: 'serenitrove',
    title: 'Serenitrove',
    description: 'Dig deeper underground, level up, and craft better tools in this addictive mining game! Collect resources and upgrade your equipment to reach greater depths.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/ASpiring.jpg',
    category: 'Strategy',
    estimatedPlayTime: '10-30 minutes',
    isPopular: true,
    isFeatured: true,
    isRecent: true,
    isBest: true,
  },
  {
    id: 'flappy-dwb',
    title: 'Flappy DWB',
    description: 'Navigate your DickWifButt through obstacles in this classic flappy bird style game! Tap or click to make your character flap and avoid the pipes.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/8ZxiKr9.jpeg',
    category: 'Arcade',
    estimatedPlayTime: '2-5 minutes',
    isPopular: true,
    isFeatured: true,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'kitty-cannon-dwb',
    title: 'Kitty Cannon DWB',
    description: 'Launch adorable kitties at targets in this physics-based puzzle game! Calculate angles and power to hit all targets.',
    difficulty: 'Easy',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/34234234.jpg',
    category: 'Puzzle',
    estimatedPlayTime: '5-15 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: true,
    isBest: false,
  },
  {
    id: 'dwb-runner',
    title: 'DWB Runner',
    description: 'Run, jump, and slide through an endless obstacle course! Collect coins and power-ups while avoiding dangerous obstacles.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/34342342.jpeg',
    category: 'Action',
    estimatedPlayTime: '3-10 minutes',
    isPopular: true,
    isFeatured: false,
    isRecent: false,
    isBest: true,
  },
  {
    id: 'abduction-game',
    title: 'Abduction Adventure',
    description: 'Help aliens abduct humans in this strategic puzzle game! Plan your moves carefully to complete each level.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/ABDUCTION.jpg',
    category: 'Strategy',
    estimatedPlayTime: '8-20 minutes',
    isPopular: false,
    isFeatured: true,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'aspiring-hero',
    title: 'Aspiring Hero',
    description: 'Embark on an epic journey to become the greatest hero! Fight monsters, collect treasures, and level up your character.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/12312312312weqwew3123.png',
    category: 'Adventure',
    estimatedPlayTime: '15-45 minutes',
    isPopular: true,
    isFeatured: false,
    isRecent: true,
    isBest: false,
  },
  {
    id: 'dead-piccolo',
    title: 'Dead Piccolo',
    description: 'A dark and atmospheric survival horror game. Navigate through a mysterious world filled with danger.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/dead piccalo.jpg',
    category: 'Horror',
    estimatedPlayTime: '20-60 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'king-kong',
    title: 'King Kong Adventure',
    description: 'Climb to the top as King Kong! Avoid obstacles and reach the highest point in this vertical climbing game.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/king kong.jpg',
    category: 'Action',
    estimatedPlayTime: '5-15 minutes',
    isPopular: true,
    isFeatured: true,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'power-rush',
    title: 'Power Rush',
    description: 'Race against time in this high-speed action game! Collect power-ups and avoid obstacles to achieve the highest score.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/Powerr.jpg',
    category: 'Racing',
    estimatedPlayTime: '3-8 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: true,
    isBest: false,
  },
  {
    id: 'squishy-world',
    title: 'Squishy World',
    description: 'Explore a world made entirely of squishy materials! Solve puzzles and discover hidden secrets in this unique adventure.',
    difficulty: 'Easy',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/Squishy.jpg',
    category: 'Puzzle',
    estimatedPlayTime: '10-25 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'pito-adventure',
    title: 'Pito Adventure',
    description: 'Join Pito on an exciting adventure through mysterious lands! Solve puzzles and overcome challenges.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/PITO.jpg',
    category: 'Adventure',
    estimatedPlayTime: '12-30 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'placeholder-1',
    title: 'Mystery Game 1',
    description: 'An exciting mystery game with unique gameplay mechanics and challenging puzzles.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/WhatsApp Image 2024-10-10222 at 18.11.45_bf26d145.jpg',
    category: 'Puzzle',
    estimatedPlayTime: '8-20 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'placeholder-2',
    title: 'Adventure Quest 2',
    description: 'Embark on a thrilling adventure with challenging quests and epic battles.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/WhatsApp Image 2024-10-16 at 18.15.08_3a7498b7.jpg',
    category: 'Adventure',
    estimatedPlayTime: '15-40 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'placeholder-3',
    title: 'Speed Racing 3',
    description: 'Race at incredible speeds through challenging tracks and compete for the best time.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/ph3.jpg',
    category: 'Racing',
    estimatedPlayTime: '5-12 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'placeholder-4',
    title: 'Puzzle Master 4',
    description: 'Test your puzzle-solving skills with increasingly difficult challenges.',
    difficulty: 'Easy',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/ph4.jpg',
    category: 'Puzzle',
    estimatedPlayTime: '10-25 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'placeholder-5',
    title: 'Action Hero 5',
    description: 'Become an action hero and fight your way through waves of enemies.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/ph5.jpg',
    category: 'Action',
    estimatedPlayTime: '8-20 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'whatsapp-game-1',
    title: 'WhatsApp Adventure 1',
    description: 'A mysterious adventure game with unique storytelling and immersive gameplay.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/ph1.jpg',
    category: 'Adventure',
    estimatedPlayTime: '15-30 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'whatsapp-game-2',
    title: 'WhatsApp Adventure 2',
    description: 'Explore new worlds and discover hidden treasures in this exciting adventure.',
    difficulty: 'Easy',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/ph2.jpg',
    category: 'Adventure',
    estimatedPlayTime: '10-25 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'whatsapp-game-3',
    title: 'WhatsApp Adventure 3',
    description: 'A thrilling journey through mysterious landscapes and challenging obstacles.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/WhatsApp Image 2024-10-16 at 18.33315.10_804590e3.jpg',
    category: 'Action',
    estimatedPlayTime: '20-40 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'whatsapp-game-4',
    title: 'WhatsApp Adventure 4',
    description: 'Navigate through complex puzzles and strategic challenges in this mind-bending game.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/WhatsApp Image 2024-10-24 at 19.39.16_df0ad8ererer8.jpg',
    category: 'Puzzle',
    estimatedPlayTime: '12-30 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'whatsapp-game-5',
    title: 'WhatsApp Adventure 5',
    description: 'Race against time in this high-octane action-packed adventure game.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/WhatsApp Image 2024-10-27 at 17.47.4339_6e2ace75.jpg',
    category: 'Racing',
    estimatedPlayTime: '5-15 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'whatsapp-game-6',
    title: 'WhatsApp Adventure 6',
    description: 'Embark on an epic quest filled with magic, monsters, and legendary treasures.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/WhatsApp Image 2024-11-01 at 18.45.36weqwew_f722efeb.jpg',
    category: 'Adventure',
    estimatedPlayTime: '25-60 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'untitled-game-1',
    title: 'Untitled Adventure 1',
    description: 'A mysterious game with unique mechanics and unexpected twists.',
    difficulty: 'Medium',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/Untitled (3).png',
    category: 'Adventure',
    estimatedPlayTime: '15-35 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
  {
    id: 'untitled-game-2',
    title: 'Untitled Adventure 2',
    description: 'Explore uncharted territories and discover ancient secrets in this epic adventure.',
    difficulty: 'Hard',
    highScore: 0,
    isAvailable: true,
    thumbnail: '/Thumbnails/Untitled (14).png',
    category: 'Adventure',
    estimatedPlayTime: '30-90 minutes',
    isPopular: false,
    isFeatured: false,
    isRecent: false,
    isBest: false,
  },
];

export const getGameById = (id: string): Game | undefined => {
  return games.find(game => game.id === id);
};

export const getAvailableGames = (): Game[] => {
  return games.filter(game => game.isAvailable);
};

export const getGamesByCategory = (category: string): Game[] => {
  return games.filter(game => game.category === category);
};

export const getGamesByDifficulty = (difficulty: string): Game[] => {
  return games.filter(game => game.difficulty === difficulty);
};

export const getPopularGames = (): Game[] => {
  return games.filter(game => game.isPopular);
};

export const getFeaturedGames = (): Game[] => {
  return games.filter(game => game.isFeatured);
};

export const getRecentGames = (): Game[] => {
  return games.filter(game => game.isRecent);
};

export const getBestGames = (): Game[] => {
  return games.filter(game => game.isBest);
};
